spring:
  application:
    name: BE_IM_Interview_Management
  datasource:
    url: jdbc:mysql://database-interview-management.c5gcocgqcjzl.ap-southeast-2.rds.amazonaws.com/Interview_Management
    username: admin
    password: 2609200303Mai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: maidx26092003@gmail.com
    password: deqshzuabxoydeoh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh

jwt:
  expiration: 7d
  secretKey: o8VF4ZOGasJGowiff2tyg5ww0ID54W5nsZrYSUFFivc=

#testMai

#testHieu